version: '3'
services:
    dmg3cdb:
      image: 'postgres:14.1-alpine'
      container_name: dmg3cdb
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB} 
      volumes:
         - ./04_Database/pgdata:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5