export const ConfigAPI = {
    getAboutUsURL:'/landingpage/aboutus',
    getManufacturingEngineeringURL:'/landingpage/me',
    getCustomerServicesURL:'/landingpage/customerservices',
    getInformationTechnologyURL:'/landingpage/it',
    getFinanceControllingURL:'/landingpage/finance',
    getCostEngineeringURL:'/landingpage/costengineering',
    getHumanResourceURL:'/landingpage/humanresource',
    getQualityManagementDetailsURL:'/landingpage/qualitymanagement/getmaincntent?ModelName=Quality Management',
    getSubCntQualityManagementURL:'/landingpage/qualitymanagement/getsubcntnt?ModelName=Quality Management',
    getleanProcessConsultantsURL:'/landingpage/lpconsultant',
    getSupplierManagementURL:'/landingpage/supplier',
    getTestimonialsURL:'/landingpage/testimonials',
    getServiceURL:'/landingpage/services',
    getVisionMission:'/landingpage/missionvisin',
    getOurCapabilities:'/landingpage/capabilities/getmaincntnt',
    getProductEngineeringURL:'/landingpage/productionengg',
    getContactsURL:'/landingpage/contacts',
    getMissionVisionURL:'/landingpage/missionvisin',
    getBrochure:'/broucher/getall',
    getServicesURL:'/landingpage/services/getmaincntent',
    getServicesSubContentURL:'/landingpage/services/getsubcntnt',
    getHumanreSourceMainCntURL:'/landingpage/humanresource/getmaincntnt?ModelName=Human Resource',
    getHumanreSourceSubCntURL:'/landingpage/humanresource/getsubcntnt?ModelName=Human Resource',
    getLeadProcessURL:'/landingpage/lpconsultant/getmaincntent?ModelName=Lead Process Consultant',
    getLeadProcessSubCntURL:'/landingpage/lpconsultant/getsubcntnt?ModelName=Lead Process Consultant',
    getSupplierDetailsURL:'/landingpage/supplier/getmaincntent?ModelName=Supplier Management',
    getSubCntSupplier:'/landingpage/supplier/getsubcntnt?ModelName=Supplier Management',
    getFinanceSubContentDetaisURL:'/landingpage/finance/getsubcntnt?ModelName=Finance Controlling',
    getMainContentFinanceURL:'/landingpage/finance/getmaincntent?ModelName=Finance Controlling',
    getOurCapabilitiesURL:'/landingpage/capabilities/getmaincntnt?ModelName=Our Capabilities',
    getManufacturingURL:'/landingpage/me/getmaincntent?ModelName=Manufacturing Engineering',
    getManufacturingSubContentURL:'/landingpage/me/getsubcntnt?ModelName=Manufacturing Engineering',
    getCostEngineeringMainContentURL:'/landingpage/costengineering/getmaincntent?ModelName=Cost Engineering',
    getCostSubContentURL:'/landingpage/costengineering/getsubcntnt?ModelName=Cost Engineering',
    getITMainContentURL:'/landingpage/it/getmaincntnt?ModelName=Information Technology',
    getCustomerServicesDetailURL:'/landingpage/customerservices/getmaincntent?ModelName=Customer Services',
    getCustomerServicesSubContentURL:'/landingpage/customerservices/getsubcntnt?ModelName=Customer Services',
    getProductMaincontentURL:'/landingpage/productionengg/getmaincntent?ModelName=Production Engineering',
    getProductSubContentURL:'/landingpage/productionengg/getsubcntnt?ModelName=Production Engineering',
    getNewLetterURL:'/newsletter/getall?ModelName=News Letter',
    getContentURL:'/content/getall?Modelname=Content',
    getLatestNewsLetterURL:'/newsletter/latestnewsletter',
    getSingleBrochureDetails:'/broucher/get',
    getSingleNewsletterDetails:'/newsletter/get',
    getSingleContentDetails:'/content/get'
}
