spring:
  datasource:
    url:  jdbc:mysql://${DB_HOST}:${DATABASE_PORT_CONTAINER}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 50
      minimum-idle: 5
      connection-timeout: 15000
      maxLifetime: 900000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

schematic:
  async:
    poolSize: 100
    queueCapacity: 20
  scheduler:
    dailyDuration: 600000
    excelDuration: 30000
    kitAssemblyValidation: 7200000

schematics:
  origins: ${WEB_URL}
  
bulkUpload:
  path: C:\Users\sriranv\Downloads\

excel:
  headers:
    a06: DTNA Circuit,SAE Circuit,Color,Source Connector,Source Cavity,Destination Connector,Destination Cavity,Description
    g06: DTNA Circuit,SAE Circuit,Color,Origin Designator,Source Connector Number,Source Cavity,Mating Designator,Destination Connector Number,Destination Cavity,Mating Connection Via,Cavity Description,Device Name
    metadata: Connector Description,Connector Numbers,Number of Cavities,Connector Type,Custom Image Names,Wire Orientation from,Pin Sequence,Connector Color
    sgmapping: S Part Name,G Part Name
  cellcount:
    a06: 8
    g06: 12
    metadata: 8
    sgmapping: 2
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show:
        details: always
