spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schematicdb
    username: root
    password: Intel@123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

schematic:
  async:
    poolSize: 100
    queueCapacity: 20
  scheduler:
    excelDuration: 120000
    dailyDuration: 600000
    kitAssemblyValidation: 7200000

bulkUpload:
  path: C:\Users\sriranv\Downloads\

schematics:
  origins: http://localhost:4200

excel:
  headers:
    a06: DTNA Circuit,SAE Circuit,Color,Source Connector,Source Cavity,Destination Connector,Destination Cavity,Description
    g06: DTNA Circuit,SAE Circuit,Color,Origin Designator,Source Connector Number,Source Cavity,Mating Designator,Destination Connector Number,Destination Cavity,Mating Connection Via,Cavity Description,Device Name
    metadata: Connector Description,Connector Numbers,Number of Cavities,Connector Type,Custom Image Names,Wire Orientation from,Pin Sequence,Connector Color
    sgmapping: S Part Name,G Part Name
  cellcount:
    a06: 8
    g06: 12
    metadata: 8
    sgmapping: 2
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show:
        details: always
logging:
  group:
    backend: com.daimler.schematicbackend
  level:
    backend: debug
  file:
    path: /Users/mprasa/Desktop/schematic_logs/
    name: mbrdi_schematic_backend.log
    max-size: 1MB
    total-size-cap: 10MB
    max-history: 30
    clean-history-on-start: false

  pattern:
    rolling-file-name: mbrdi_schematic_backend-%d{yyyy-MM-dd}.%i.log
