export const ConfigAPI = {
    login: '/auth/signin',
    logout: '/auth/logout',
    forgetpassword: '/auth/forgotpassword', //NOSONAR
    resetpassword: '/auth/reset-password', //NOSONAR
    getLeadsDetailList: '/leadrequest',
    getUserDetails: '/employees/getuser',
    leadsAssignuer: '/leadrequest/assignuser/',
    checkauth: '/employees/checktokenvalid',
    businesscaserequest: '/businesscaserequest',
    bizMultiProv: '/businesscaserequest/multiproviderapproval',
    bizSingalProv: '/businesscaserequest/singalproviderapproval',
    bizApprovalPut: '/auth/approvals/',
    bizApprovalGet: '/businesscaserequest/approval/',
    hrUserDetail: '/employees/getuserbyrole/HR',
    facilityUserDetail: '/employees/getuserbyrole/FACILITY',
    existingRateCard: '/ratecard',
    itUserDetail: '/employees/getuserbyrole/IT',
    createBizRequirement: '/businesscaserequest/',
    getBizRequirement: '/businesscaserequest/',
    updateBizRequirement: '/businesscaserequest/update/',
    saveAndNotifyBizRequirement: '/businesscaserequest/saveandnotify/',
    saveAndNotifyAllBizRequirement: '/businesscaserequest/saveandnotifyfull/',
    getIterationDetails: '/businesscaserequest/getiterationlevel/',
    removeDocs: '/leadrequest/removedocs/',
    resendEmail: '/businesscaserequest/resendemail/',
    leadConversionAverage: '/leadrequest/leadConversionAverage',
    getDepartment: '/leadrequest/getdepartment',
    getJDProjectDetails: '/jobdescription/',
    createBizJDMapping: '/jobdescription/bulkinsertorupdate/',
    updateBizJDMapping: '',
    removeBizJDFile: '/jobdescription/removedocs/',
    getBizJDMapAssigningDetails: '/jobdescription/jdmapping/',
    setJDMapAssign: '/jobdescription/saveorupdatejdmapping/',
    setJDFileUpload: '/fileupload/upload',
    getJDListData: '/jobdescription/getalljd/',
    getStepperAPI: '/leadrequest/getoverallstatus/',
    getProject: '/project/getproject',
    getprojectoverview: '/project/getprojectoverview/',
    getProjectList: '/project/getprojectslist',
    getResourceAllocationURL: '/resourceallocation/getresourcemapping/',
    getSLADetails: '/resourceallocation/getsla/',
    postResourceAllocation: '/resourceallocation',
    //capacity management
    getCapacityManagement: '/resourceallocation/getprojectsview',
    getSLAViews: '/resourceallocation/getslasview',
    getResourceView: '/resourceallocation/getresourceview',
    // timesheet services
    getTimesheetProject: '/timesheet/getprojectsbillablehrs',
    getTimesheetSlaList: '/timesheet/getslas',
    getTimesheetTaskList: '/timesheet/gettaskbysla/',
    getTimesheet: '/timesheet',
    getTimesheetByProject: '/timesheet/getbyproject/',
    //This is list Task services
    postTask: '/task',
    getTaskList: '/task/gettask/',
    getTaskProject: '/task/getprojects',
    getSLAByProject: '/task/getslabyproject/',
    getResourceList: '/task/getresourcebysla/',
    taskFileUpload: '/fileupload/upload',
    getCostCenter: '/resource/getcostcenter',
    getResourceReport: '/resource/getresourcereport',
    getResourceProjectReport: '/resourcereport/getresourcerecord',
    ResoureceSkillUpdate: '/resourcereport/resourceupdate/',
    /** BizCase SLA */
    getAllBizCase: '/sla',
    createBizCaseSLA: '/sla/',
    updateBizCaseSLA: '/sla/',
    getBizCaseSLA: '/sla',
    customerBizCaseSLA: '/customer/getnames',
    MaterialBizCaseSLA: '/materialcode/getnames',
    costCenterBizCaseSLA: '/costcenter/getlist',
    /** PreInvoice  */
    getAllPreInvoice: '/sla/slapreinvoice',
    getEditPreInvoice: '/sla/slapreinvoicebysla',
    getAllInvoice: '/sla/slainvoice',

    /** Businesscase setup  */
    getBizCaseSetupData: '/businesscasesetup/',
    getAllRoleMappedUsers: '/employees/getuserswithrole',
    getUsersWoRole: '/employees/getuserswithoutrole',
    getAllRolesList: '/employees/getroles',
    createUserRoleMapping: '/employees/assignrole',
    getBizCaseSetup: '/businesscasesetup/getbizcasesetupinfo/',
    getUtilizationData: '/resourcereport/getutilizationreport',
    getEmployeeDetails: '/resourcereport/getemployee/',
    mapResourceData: '/resourceallocation/addresource/',
    updateResourceAllocation: '/resourceallocation/updateresourceallocation/',
    addThirdPartResource: '/employees/addthirdpartyresource',
    getViewThirdoartyResource: '/employees/thirdpartyresource/',
    upateThirdParty: '/employees/updatethirdpartyresource/',
    deletethirdpartyemployee: '/employees/deletethirdpartyemployee',
    // Finance
    getAllbizRateCard: '/bizratecard',
    getBizRateCardInfo: '/bizratecard/getratecard/',
    updateBizRateCardInfo: '/bizratecard/updaterateinfo/',
    getAccurals: '/accurals',
    getAccuralsDetail: '/accurals/getslabyproject/',
    getAccuralsSLADetails: '/accurals/slaaccurals/',
    updateAccuralsSLADetails: '/accurals/update',
    uploadAccuralsDump: '/accurals/slaaccurals/',
    getAccuralsDump: '/accurals/download/',
    financeAddCostCenter: '/costcenter/blukinsert',
    financeCostCenter: '/costcenter',
    financeUploadOldCostCenter: '/costcenter/addnewcostcenter',
    financeNewUploadCostCenter: '/costcenter/addcostcenter',
    //Forex Rates
    forexRates: '/forexRates',
    forexRatesUploadcsv: '/forexRates/uploadcsv',
    forexRatesBulkinsert:'/forexRates/bulkinsert',
    //iomapping
    iomapping: '/iomapping',
    iomappinguploadcsv: '/iomapping/uploadcsv',
    iomappingwithproject: '/iomapping/iomappingwithproject',
    iomappingProjects: '/iomapping/getallprojects',
    getAllCostCenterYTD: '/ccdump',
    getCostCenterDump: 'api/ccdump/download',
    getCostCenterYTDDetail: '/ccdump/',
    uploadCostCenterYTD: '/ccdump/uploadnewccdump',


    getAboutUsURL:'/landingpage/aboutus',
    getManufacturingEngineeringURL:'/landingpage/me',
    getCustomerServicesURL:'/landingpage/customerservices',
    getInformationTechnologyURL:'/landingpage/it',
    getFinanceControllingURL:'/landingpage/finance',
    getCostEngineeringURL:'/landingpage/costengineering',
    getHumanResourceURL:'/landingpage/humanresource',
    getQualityManagementDetailsURL:'/landingpage/qualitymanagement/getmaincntent?ModelName=Quality Management',
    getSubCntQualityManagementURL:'/landingpage/qualitymanagement/getsubcntnt?ModelName=Quality Management',
    getleanProcessConsultantsURL:'/landingpage/lpconsultant',
    getSupplierManagementURL:'/landingpage/supplier',
    getTestimonialsURL:'/landingpage/testimonials',
    getServiceURL:'/landingpage/services',
    getVisionMission:'/landingpage/missionvisin',
    getOurCapabilities:'/landingpage/capabilities/getmaincntnt',
    getProductEngineeringURL:'/landingpage/productionengg',
    getContactsURL:'/landingpage/contacts',
    getMissionVisionURL:'/landingpage/missionvisin',
    getBrochure:'/broucher/getall',
    getServicesURL:'/landingpage/services/getmaincntent',
    getServicesSubContentURL:'/landingpage/services/getsubcntnt',
    getHumanreSourceMainCntURL:'/landingpage/humanresource/getmaincntnt?ModelName=Human Resource',
    getHumanreSourceSubCntURL:'/landingpage/humanresource/getsubcntnt?ModelName=Human Resource',
    getLeadProcessURL:'/landingpage/lpconsultant/getmaincntent?ModelName=Lead Process Consultant',
    getLeadProcessSubCntURL:'/landingpage/lpconsultant/getsubcntnt?ModelName=Lead Process Consultant',
    getSupplierDetailsURL:'/landingpage/supplier/getmaincntent?ModelName=Supplier Management',
    getSubCntSupplier:'/landingpage/supplier/getsubcntnt?ModelName=Supplier Management',
    getFinanceSubContentDetaisURL:'/landingpage/finance/getsubcntnt?ModelName=Finance Controlling',
    getMainContentFinanceURL:'/landingpage/finance/getmaincntent?ModelName=Finance Controlling',
    getOurCapabilitiesURL:'/landingpage/capabilities/getmaincntnt?ModelName=Our Capabilities',
    getManufacturingURL:'/landingpage/me/getmaincntent?ModelName=Manufacturing Engineering',
    getManufacturingSubContentURL:'/landingpage/me/getsubcntnt?ModelName=Manufacturing Engineering',
    getCostEngineeringMainContentURL:'/landingpage/costengineering/getmaincntent?ModelName=Cost Engineering',
    getCostSubContentURL:'/landingpage/costengineering/getsubcntnt?ModelName=Cost Engineering',
    getITMainContentURL:'/landingpage/it/getmaincntnt?ModelName=Information Technology',
    getCustomerServicesDetailURL:'/landingpage/customerservices/getmaincntent?ModelName=Customer Services',
    getCustomerServicesSubContentURL:'/landingpage/customerservices/getsubcntnt?ModelName=Customer Services',
    getProductMaincontentURL:'/landingpage/productionengg/getmaincntent?ModelName=Production Engineering',
    getProductSubContentURL:'/landingpage/productionengg/getsubcntnt?ModelName=Production Engineering',
    geAlltNewLetterURL:'/newsletter/getall?ModelName=News Letter',
    getAllContentURL:'/content/getall?Modelname=Content',
    getLatestNewsLetterURL:'/newsletter/latestnewsletter',
    getSingleBrochureDetails:'/broucher/get',
    getSingleNewsletterDetails:'/newsletter/get',
    getSingleContentDetails:'/content/get',
    geAlltNewLetterCommon:'/newsletter/getall',
    getAllContentURLCommon:'/content/getall',
    //vendor
    vendor:'/vendor',
    addnewvendor:'/vendor/addnewvendor',
    addvendor:'/vendor/addvendor',
    vendorBulkinsert:'/vendor/bulkinsert',
    updateVendor:'/vendor/update',
    //RateCard
    ratecard:'/ratecard',
    ratecardupload:'/ratecard/uploadcsvfile',
    getRatecardDetails:'/ratecard/getratecard',
    ratecardBulkinsert:'/ratecard/bulkinsert',
    ratecardBulkmodify:'/ratecard/bulkmodify',
    //IO Dump
    iodump:'/iodump',
    iodumpBulkinsert:'/iodump/bulkinsert',
    iodumpDownload:'api/iodump/download',
    getAllEntityMaster: '/customer',
    getAllMaterialMaster: '/materialcode',
    bizCaseInfoByProjectId:'/businesscasesetup/bizcaseinfobyprojectid',
    getEntityMasterDump: 'api/customer/download',
    getMaterialMasterDump: 'api/materialcode/download',
    createEntityMaster: '/customer/create',
    updateEntityMaster: '/customer/update/',
    createMaterialMaster: '/materialcode/create',
    updateMaterialMaster: '/materialcode/update/',
    uploadEntityMasterDump: '/customer/addnewcustomermaster',
    uploadMaterialMasterDump: '/materialcode/uploadnewmaterialcode',
    getResourceDetail:'/resourcereport/getresource',
    iodumpUpload:'/iodump/uploadnewiodump',
    jdDetails:'/businesscasesetup/jddetails/',
    postHRsetupDetails:'/businesscasesetup/getunhiredjd/',
    // Project Owner Module    
    getAllProjectOwnerDetails: '/employees/getbussinessmanagergrid',
    getProjectOwnerDetail: '',
    updateProjectOwnerDetail: '',
    getBusinessUsersList: '/employees/getbussinessmanager/',
    postTaskUpdate:'/task/settaskstatus',
    setCapinitiandTask:'/resourceallocation/setcapinitiandtask',
    slapreinvoicedropdown:'/sla/slapreinvoicedropdown/',
    slapreinvoiceinfo:'/sla/slapreinvoiceinfo',
    slapreinvoice:'/sla/slapreinvoice/',
    setBizCaseCalculation: '/bizpreview/save/',
    getProfiltandLossDetails: '/bizpreview/getratecardreport/',
    getProfiltandLossIterationList: '/bizpreview/getiterationlist/',
    getProfiltandLossIterationDetail: '/bizpreview/getiterationreport/',
    setFinalProfitandLossIterationDetail: '/bizpreview/saveactiveiteration/',
    getprojectdetails:'/sla/getprojectdetails/',
    getOrganization:'/mysscdata/organization',
    getBillingcycle:'/mysscdata/billingcycle',
    setWithoutBizCase: '/businesscaserequest/withoutbizcase/',
    setIterationRampup: '/businesscaserequest/setiterationrampup/',
    getFinanceUsersList: '/bizratecard/getfinancerole',
    sendFinanceMail: '/bizratecard/sendmailfinance/',
    getcustomerandbusiness:"/employees/getcustomerandbusiness",    
    putJDMappingInternalhire:"/businesscasesetup/internalhire",
    costCenterDownload: 'costcenter/download',
    rateCardMasterDownload: 'api/ratecard/download',
    forexRatesDownload: 'api/forexRates/download',
    vendorMasterDownload: 'api/vendor/download',
    ioMappingdumpDownload:'api/iomapping/download',
    updateSLAContractStatus: '/sla/updatecontractoption/',
    updateSLAContacts: '/sla/updatecontacts/',
    createPreInvoiceDetail: '/sla/slapreinvoice/',
    slaC4dUpload: '/sla/c4dsla',
    getSLAC4dDetails: '/sla/savec4dsla/',
    commonFileUpload: '/fileupload/upload',
    dashboardDetails:'/dashboard/maindashboard',
    downloadThirdPartyResource:'/employees/downloadthirdpartyresource',
    uploadThirdPartyResource:'/employees/uploadthirdpartyresource',
    getMatericalDescriptionURL:'/materialcode/getmaterialcode',
    getCountryListUrl:'/slacountry',
    getContractListUrl:'/slacontract',
    getCurrecncyUrl:'/ratecard/bycurrency',
    getProvisionCostCenter: '/provisions/getcostcenter',
    getProvisionsStatus: '/provisionstatus',
    getProvisionsDetails: '/provisions',
    updateProvisionDetails: '/provisions/update',
    downloadProvisionArchieve: '/provisions/provisionarchivereport',
    checkAddProvisionDetail: '/provisions/checkaddprovision',
    downloadProvisionOverallReport: '/provisions/provisionreport',
    getProvisionOverallReport: 'provisions/barchartreport',
    updateSLAContactsURL: '/sla/updatesla/',
    getBusinessCaseReport:'/businesscasesetup/dashboard/',
    getIOChartURL:'/iodump/barchartreport',
    getCCChartURL:'/ccdump/barchartreport',
    getCustomerBizReport: '/report/downloadcustomerreport',
    getLeadBizReport: '/report/downloadleadreport',
    getDetailedBizExcelReport: '/report/downloadbizcasereport/',
    getDetailedBizPdfReport: '',
    getBizSetupReport: '',
    getNewBizRecruitmentReport: '',
    getBizCaseDetailsListReport: '/businesscaserequest/getbizinfo',    
    getSLADetailsReport: '/report/slareport',    
    getOperationResourceReports: '/report/generalresourcereport',    
    getOperationCapacityReports: '/report/downloadcapacityreport',    
    getOperationPositionsReports: '/report/downloadpositionsreport?cost_center=',    
    getOperationTimesheetCostCenterReports: '/report/downloadtimesheetreport?cost_center=',    
    getOperationTimesheetShortIDReports: '/report/downloadtimesheetreport?short_id=',    
    getOperationTaskReports: '/report/downloadtaskreport/',
    getCostCenterListDetails: '/businesscaserequest/getcostcenter',
    getShortIDListDetails: '/employees/getemployees',
    getProjectsListDetails: '/report/getprojects',
    getMarketDataURL:'/g3cmarketvalue',
    getAssignRoleURL:'/employees/assignrole',
    getUserswithoutroleURL:'/employees/getuserswithoutrole',
    getuserswithroleURL:'/employees/getuserswithrole',
    getRolesURL:'/employees/getroles',
    getRevenueSummaryReport: '/report/revenuereport?year=',
    getAccuralsReport: '/accurals/accuralsexport',
    getTravelCostReport: '/report/travelcostreport/',
    getMaterialRevenueExpenseReport: '/report/downloadmaterialreport',
    getManpowerSkillSetReport: '/report/downloadmanpowerreport',
    getBenchResourceReport: '/report/downloadbenchreport',
    getAttritionReport: '/report/downloadattritionreport',
    getSLAContractsList: '/slacontract',
    getSLACountrysList: '/slacountry',
    getQualityManagementURL:'/landingpage/qualitymanagement',
    urlAboutFileUpload:'/landingpage/aboutus/singlefileupload',
    urlBroucherFileUpload:'/broucher/singlefileupload',
    urlCapabilitiesFileUpload:'/landingpage/capabilities/singlefileupload',
    urlContactsFileUpload:'/landingpage/contacts/singlefileupload',
    urlCostengineeringFileUpload:'/landingpage/costengineering/singlefileupload',
    urlCustomerservicesFileUpload:'/landingpage/customerservices/singlefileupload',
    urlFeedbackFileUpload:'/feedback/singlefileupload',
    urlFinanceFileUpload:'/landingpage/finance/singlefileupload',
    urlNewsletterFileUpload:'/newsletter/singlefileupload',
    urlHumanresourceFileUpload:'/landingpage/humanresource/singlefileupload',
    urlITFileUpload:'/landingpage/it/singlefileupload',
    urlLpconsultantFileUpload:'/landingpage/lpconsultant/singlefileupload',
    urlMeFileUpload:'/landingpage/me/singlefileupload',
    urlMissionvisinFileUpload:'/landingpage/missionvisin/singlefileupload',
    urlProductionenggFileUpload:'/landingpage/productionengg/singlefileupload',
    urlQualitymanagementFileUpload:'/landingpage/qualitymanagement /singlefileupload',
    urlServicesFileUpload:'/landingpage/services/singlefileupload',
    urlSupplierFileUpload:'/landingpage/supplier/singlefileupload',
    urlTestimonialsFileUpload:'/landingpage/testimonials/singlefileupload',
    removePushNotification: '/auth/removenotification/',
    createNewCustomer: '/auth/createcustomer',
    getCommonGetAPI: '/auth/createcustomer',
    aboutusFileUploadURL:'/landingpage/aboutus/singlefileupload',
    aboutUsURL:'/landingpage/aboutus',
    capabilitiesURL:'/landingpage/capabilities/getmaincntnt',
    capabilitiesUploadURL:'/landingpage/capabilities/singlefileupload',
    capabilitiesSubCantentURL:'/landingpage/capabilities/updatesubcntnt',
    capabilitiesMainCantentURL:'/landingpage/capabilities/maincntnt',
    capabilitiesDeleteURL:'/landingpage/capabilities/deletemaincntnt/',
    cantactsUploadImage:'/landingpage/contacts/singlefileupload',
    contactsURL:'/landingpage/contacts',
    broucherUploadURL:'/broucher/singlefileupload',
    broucherURL:'/broucher/getuserbroucher',
    addBroucherURL:'/broucher',
    broucherLatestURL:'/broucher/latestbroucher',
    broucherActiveURL:'/broucher/activebroucher',
    missionVisionURL:'/landingpage/missionvisin',
    missionVisonUploadURL:'/landingpage/missionvisin/singlefileupload',
    //cost engineering
    costEngineeringMainContentURL:'/landingpage/costengineering/maincntnt',
    costEngineeringUpdateURL:'/landingpage/costengineering/updatesubcnt',
    costEngineeringDeleteSubcontentURL:'/landingpage/costengineering/deletesubcntnt/',
    getCostEngineeringSubContentURL:'/landingpage/costengineering/getsubcntn',
    postCostEngineerSubContentURL:'/landingpage/costengineering/subcntnt',
    deletSubListURL:'/landingpage/costengineering/deletesublist/',
    postServicesURL:'/landingpage/services/maincntnt',
    updateSubContentURL:'/landingpage/services/updatesubcntnt',
    postServicesSubContentURL:'/landingpage/services/subcntnt',
    deleteSubContentURL:'/landingpage/services/deletesubcntnt',
    uploadServicesImageURL:'/landingpage/services/upload',
    deleteSubServicesURL:'/landingpage/services/deletesubcntnt/',
    ///Manufacturing
    getManufacturingSub:'/landingpage/me/subcntnt',
    postManufacturingSubContentURL:'/landingpage/me/updatesubcntnt',
    deleteManufacturingSubContentURL:'/landingpage/me/deletesubcntnt/',
    postManufacturingMainContentURL:'/landingpage/me/maincntnt',
    postProductSubContentURL:'/landingpage/productionengg/subcntnt',
    putProductSubContentURL:'/landingpage/productionengg/updatesubcntnt',
    deletesubcontentProductionURL:'/landingpage/productionengg/deletesublist/',
    postProductMainConterURL:'/landingpage/productionengg/maincntnt',
    putCustomerServicesURL:'/landingpage/customerservices/updatesubcnt',
    deleteCustomerSubContentURL:'/landingpage/customerservices/deletesubcntnt/',
    postCustomerServicesSubContentURL:'/landingpage/customerservices/subcntnt',
    postCustomerServicesMainContentURL:'/landingpage/customerservices/maincntnt',
    postITMainContentURL:'/landingpage/it/maincntnt',
    deleteITMainContent:'/landingpage/it/deletemaincntnt/',
    deleteSubContentFinanceURL:'/landingpage/finance/deletesubcntnt/',
    postSubContentFinanceURL:'/landingpage/finance/subcntnt',
    putSubContentFinanceURL:'/landingpage/finance/updatesubcnt',
    postMainContentFinanceURL:'/landingpage/finance/maincntnt',
    postQualityManagementSubCntURL:'/landingpage/qualitymanagement/subcntnt',
    putQualityManagementSubCntURL:'/landingpage/qualitymanagement/updatesubcntnt',
    postQualityManagementMainURL:'/landingpage/qualitymanagement/maincntnt',
    deleteQualitySubContentURL:'/landingpage/qualitymanagement/deletesubcntnt/',
    putLeadProcessSubcntURL:'/landingpage/lpconsultant/updatesubcntnt',
    postLeadProcessSubCntURL:'/landingpage/lpconsultant/subcntnt',
    deleteLeadProcessSubCntURL:'/landingpage/lpconsultant/deletesubcntnt/',
    postLeadProcessURL:'/landingpage/lpconsultant/maincntnt',
    postSupplierURL:'/landingpage/supplier/maincntnt',
    postSubCntSupplier:'/landingpage/supplier/subcntnt',
    putSubCntSupplier:'/landingpage/supplier/updatesubcntnt',
    deleteSubContentSupplier:'/landingpage/supplier/deletesubcntnt',

    postTestimonialURL:'/landingpage/testimonials',
    getTestimonialsDetailsURL:'/landingpage/testimonials',
    uploadTestimonialImageURL:'/landingpage/testimonials/singlefileupload',
    uploadTestmonialURL:'/landingpage/testimonials/singlefileupload',
    deleteTestmonialURL:'/landingpage/testimonials/',

    uploadNewsletterURL:'/newsletter/singlefileupload',
    activeNewsletterURL:'/newsletter/activenewsletter',
    postNewsletterURL:'/newsletter',
    getNewLetterURL:'/newsletter/getusernewsletter?ModelName=News Letter',
    deleteNewsLetterURL:'/newsletter',

    getHumanResourceSubCntURL:'/landingpage/humanresource/getsubcntnt?ModelName=Human Resource',
    putHumanResourceSubCntURL:'/landingpage/humanresource/updatesubcntnt',
    postSubcntHumanResourceURL:'/landingpage/humanresource/subcntnt',
    deleteSubCntHumanResourceURL:'/landingpage/humanresource/deletesubcntnt/',
    getHumanResourceMainCntURL:'/landingpage/humanresource/getmaincntnt?ModelName=Human Resource',
    postHumanResourceURL:'/landingpage/humanresource/maincntnt',

    feedbackURL:'/feedback',
    contentURL:'/content',
    getContentURL:'/content/getusercontent?ModelName=Content',
    exportExcelFileFeedback:'/feedback/excelreport',
    ioMappingBizRequest:'/businesscaserequest/updatejdmapping/',

    newsletterApproval:'/newsletter/approvenewsletter',
    brochureApproval:'/broucher/approvebroucher',
    contentApproval:'/content/approvecontent',
    getBizInforeportAPI:'/businesscaserequest/getbizinforeport',
    getDownloadRecruitments:'/report/downloadrecruitmentreport',
    removeProvisionData:'/provisions/removeprovision/',
    jddeletedapi:'/jobdescription/deletejd/',
    sendMailToled:'/leadrequest/sendemailtolead',
    getProjectsProvision:'/provisions/getprojects/',
    getSlabyproject:'/provisions/getslabyproject/',
    slaApprovalUrl:'/auth/sla/approvals/',
    reopenTaskDetails:'/task/reopen',
    getPreInvoiceApproval:'/sla/getpreinvoiceapprovestatus/',
    getSLAApproval:'/sla/getslaapprovestatus/',
    deleteCostCenter:'/costcenter/delete/',
    getTimesheetExcelReport:'/timesheet/excelreport/',
    getVendorListAPI:'/vendor/vendorlist',
    expensereportAPI:'/iomapping/expensereport/' 
}
