export const option: any = ["123", "12345"]

export const resourcerecordlist:any = [
    {
        "id":1,
        "hr_id":"HR001",
        "employee":"Sathish",
        "email":"Sathish@mailinator.com",
        "skill":"PC00111",
        "job_category":"TATA",
        "doj":"12/02/2021",
        "rev_generated":"test"
      },
      {
        "id":2,
        "hr_id":"HR002",
        "employee":"vinoth",
        "email":"vinoth@mailinator.com",
        "skill":"PC00111",
        "job_category":"TATA",
        "doj":"12/02/2021",
        "rev_generated":"test"
      },
      {
        "id":3,
        "hr_id":"HR003",
        "employee":"Mani",
        "email":"mani@mailinator.com",
        "skill":"PC00111",
        "job_category":"TATA",
        "doj":"12/02/2021",
        "rev_generated":"test"
      }
]

export const resourceRecordList:any = [
  {
    "id":1,
    "UnderProject":"TATA",
    "CurrentProject":"BMW",
    "SLAStartDate":"12-06-2021",
    "SLAEndDate":"12-06-2022",
    "ResourceStatus":"Completed",
    "BillingRate":"Rs.10000000",
    "EmployeeLeaveTaken":"L1",
    "LossOfBillingDueToLeave":"test",
    "TotalLossOfBilling":"Rs.120000",
    "Overtime":"12:30PM",
    "OvertimeCost":"Rs.3000",
    "TotalBillingShortage":"30",
    "EfficiencyMeasure":"tes",
    "NEndSLAdays":"12",
    "VisibilityofNextSLA":"13",
    "SLAvsCoreshare":"test"
  },
  {
    "id":2,
    "UnderProject":"TATA",
    "CurrentProject":"BMW",
    "SLAStartDate":"12-06-2021",
    "SLAEndDate":"12-06-2022",
    "ResourceStatus":"Completed",
    "BillingRate":"Rs.10000000",
    "EmployeeLeaveTaken":"L1",
    "LossOfBillingDueToLeave":"test",
    "TotalLossOfBilling":"Rs.120000",
    "Overtime":"12:30PM",
    "OvertimeCost":"Rs.3000",
    "TotalBillingShortage":"30",
    "EfficiencyMeasure":"tes",
    "NEndSLAdays":"12",
    "VisibilityofNextSLA":"13",
    "SLAvsCoreshare":"test"
  },
  {
    "id":3,
    "UnderProject":"TATA",
    "CurrentProject":"BMW",
    "SLAStartDate":"12-06-2021",
    "SLAEndDate":"12-06-2022",
    "ResourceStatus":"Completed",
    "BillingRate":"Rs.10000000",
    "EmployeeLeaveTaken":"L1",
    "LossOfBillingDueToLeave":"test",
    "TotalLossOfBilling":"Rs.120000",
    "Overtime":"12:30PM",
    "OvertimeCost":"Rs.3000",
    "TotalBillingShortage":"30",
    "EfficiencyMeasure":"tes",
    "NEndSLAdays":"12",
    "VisibilityofNextSLA":"13",
    "SLAvsCoreshare":"test"
  },
  {
    "id":4,
    "UnderProject":"TATA",
    "CurrentProject":"BMW",
    "SLAStartDate":"12-06-2021",
    "SLAEndDate":"12-06-2022",
    "ResourceStatus":"Completed",
    "BillingRate":"Rs.10000000",
    "EmployeeLeaveTaken":"L1",
    "LossOfBillingDueToLeave":"test",
    "TotalLossOfBilling":"Rs.120000",
    "Overtime":"12:30PM",
    "OvertimeCost":"Rs.3000",
    "TotalBillingShortage":"30",
    "EfficiencyMeasure":"tes",
    "NEndSLAdays":"12",
    "VisibilityofNextSLA":"13",
    "SLAvsCoreshare":"test"
  }
]